### ISSUE TITLE
assert isinstance(td, c_ast.TypeDecl)

### ISSUE THREAD

**Issue by jiffe** [inducer/pycparserext#18]
The following test code is generating an assertion error:

```
from pycparserext import GnuCParser

text = """
struct a {
    int *b[1][1];
};
"""

parser = GnuCParser()
parser.parse(text, "test.c")
```

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    parser.parse(text, "test.c")
  File "/home/jdevine/projects/python/pycparserext/ext_c_parser.py", line 64, in parse
    return self.cparser.parse(text, lexer=self.clex, debug=debuglevel)
  File "/home/jdevine/projects/python/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/jdevine/projects/python/pycparser/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/home/jdevine/projects/python/pycparserext/ext_c_parser.py", line 280, in p_declarator_2
    decl.type = TypeDeclExt.from_pycparser(decl.type)
  File "/home/jdevine/projects/python/pycparserext/ext_c_parser.py", line 162, in from_pycparser
    assert isinstance(td, c_ast.TypeDecl)
AssertionError

**Comment by inducer** [comment]
I'd be happy to take a patch.

**Comment by jiffe** [comment]
What is p_declarator_2 trying to accomplish?  This parses fine if I use pycparser so the GnuCParser looks like its adding something that's catching this and maybe shouldn't.

**Comment by inducer** [comment]
Thanks for the report!
