### ISSUE TITLE
error while importing from  pycparser.plyparser import parameterized

### ISSUE THREAD

**Issue by VerifierIntegerAssignment** [inducer/pycparserext#34]
File "./xxxxyyy.py", line 4, in <module>
    import viap_svcomp
  File "/Users/X/Downloads/X/viap_svcomp.py", line 88, in <module>
    from pycparserext.ext_c_parser import GnuCParser
  File "/Users/X/Downloads/X/packages/pycparserext/pycparserext/ext_c_parser.py", line 185, in <module>

**Comment by inducer** [comment]
I can't even see the error message in this. Please post the full traceback.

**Comment by VerifierIntegerAssignment** [comment]
SOURCE FILE---
sys.path.append(currentdirectory+"/packages/ply/")
sys.path.append(currentdirectory+"/packages/plyj/")
sys.path.append(currentdirectory+"/packages/pyparsing/")
sys.path.append(currentdirectory+"/packages/pycparser/")
sys.path.append(currentdirectory+"/packages/pycparserext/")

from pycparser import parse_file,c_parser, c_ast, c_generator
from pycparserext.ext_c_parser import GnuCParser
from pycparserext.ext_c_generator import GnuCGenerator
SOURCE FILE--------

Error occured at "from pycparserext.ext_c_generator import GnuCGenerator"

197host163:viap viap$ ./viap_tool.py
Traceback (most recent call last):
  File "./viap_tool.py", line 4, in <module>
    import viap_svcomp
  File "/Users/viap/Downloads/viap/viap_svcomp.py", line 88, in <module>
    from pycparserext.ext_c_parser import GnuCParser
  File "/Users/viap/Downloads/viap/packages/pycparserext/pycparserext/ext_c_parser.py", line 9, in <module>
    from pycparser.plyparser import parameterized, template
ImportError: cannot import name parameterized

**Comment by inducer** [comment]
Upgrade your pycparser.
