### ISSUE TITLE
installation error pycparserext 

### ISSUE THREAD

**Issue by BollimpalliSuryateja** [inducer/pycparserext#44]
>>>>> export PYTHONPATH="/home/ebolsur/desktop/pycparser/lib/python2.7/site-packages/"
>>>>> python setup.py install --prefix /home/ebolsur/desktop/pycparser 
running install

.
.
.
.
.
.
.
Installed /home/ebolsur/desktop/pycparser/lib/python2.7/site-packages/pycparserext-2016.2-py2.7.egg
Processing dependencies for pycparserext==2016.2
Searching for ply>=3.4
Reading http://pypi.python.org/simple/ply/
Couldn't find index page for 'ply' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for ply>=3.4
Best match: None
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    packages=["pycparserext"])
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 76, in run
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 104, in do_egg_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 211, in run
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 478, in install_item
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 519, in process_distribution
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 563, in resolve
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 799, in best_match
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 811, in obtain
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 434, in easy_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 475, in fetch_distribution
**AttributeError: 'NoneType' object has no attribute 'clone**'

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Investigate updating setuptools. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by BollimpalliSuryateja** [comment]
Can you please add details of mailing list in Readme.

**Comment by inducer** [comment]
Have you tried updating setuptools? What happens if you try to `pip install django` (for example)?

**Comment by BollimpalliSuryateja** [comment]
Sorry but the problem still exists

python setup.py install --prefix /home/ebolsur/desktop/pycparser

Processing dependencies for pycparserext==2019.1
Searching for ply>=3.4
Reading http://pypi.python.org/simple/ply/
Couldn't find index page for 'ply' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for ply>=3.4
Best match: None
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    packages=["pycparserext"])
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/app/python/2.7.3/LMWP3/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 76, in run
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 104, in do_egg_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 211, in run
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 478, in install_item
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 519, in process_distribution
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 563, in resolve
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 799, in best_match
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 811, in obtain
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 434, in easy_install
  File "/app/python/2.7.3/LMWP3/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'

**Comment by inducer** [comment]
Since the error does not occur in pycparserext, I would recommend that you contact the setuptools crowd for support.
